/********************************************************************************
 * INTENT-TYPE USED FOR NSP DEVICE CONFIGURATION (ICM)
 *   Vendor: {{ vendor }}
 *   Device families: {{ family }}
 *   Device version: {{ version }}
 * 
 * DISCLAIMER:
 *   This intent-type was auto-generated by the NSP Intent Manager extension
 *   for vsCode. Current status of product-specific intent-types generated
 *   using Visual Studio Code is experimental!
 * 
 *   To use in production environments, extended testing must be considered:
 *   functionality, robustness, usability, performance, and scale.
 * 
 *   If you find issues around the generator tool or the generated intent-
 *   types, please provide feedback directly to the GitHub repository or
 *   contribute your code changes!
 * 
 * (c) 2025 by Nokia
 ********************************************************************************/

import { IntentHandler }  from 'common/IntentHandler.mjs';
import { NSP } from 'common/NSP.mjs';

class CustomIntentHandler extends IntentHandler {
    constructor() {
        super();
        NSP.checkRelease(24, 11);
    }

    toMdCli(sitesConfigs) {

        // ---------- Helper: strip module prefixes ("nokia-conf:xxx") ----------
        const stripModulePrefixes = (val) => {
            if (Array.isArray(val)) return val.map(stripModulePrefixes);
            if (val && typeof val === "object") {
                const out = {};
                for (const [k, v] of Object.entries(val)) {
                    const cleanKey = k.includes(":") ? k.split(":")[1] : k;
                    out[cleanKey] = stripModulePrefixes(v);
                }
                return out;
            }
            return val;
        };

        // ---------- Helper: deep merge ----------
        const mergeDeep = (target, source) => {
            for (const [k, v] of Object.entries(source)) {
                if (Array.isArray(v)) {
                    if (!Array.isArray(target[k])) target[k] = [];
                    target[k].push(...v);
                } else if (v && typeof v === "object") {
                    if (!target[k] || typeof target[k] !== "object" || Array.isArray(target[k])) {
                        target[k] = {};
                    }
                    mergeDeep(target[k], v);
                } else {
                    target[k] = v;
                }
            }
            return target;
        };

        // ---------- FIX 2: collapse double containers (service/service) ----------
        const collapseDoubleContainer = (parent, keySeg, cleaned) => {
            if (
                cleaned[keySeg] &&                      // cleaned contains same top-level key
                typeof cleaned[keySeg] === "object" &&
                !Array.isArray(cleaned[keySeg])
            ) {
                return cleaned[keySeg];                 // collapse one level
            }
            return cleaned;
        };

        // ---------- Convert op tree into merged config tree ----------
        const buildTreeFromOps = (opsForDevice) => {
            const tree = {};

            for (const opWrapper of Object.values(opsForDevice)) {
                if (!opWrapper || typeof opWrapper !== "object") continue;

                const { target, value } = opWrapper;
                if (!target || !value) continue;

                const [, rawPath] = target.split(":");
                const path = rawPath || target;
                const segments = path.split("/").filter(Boolean);

                let cursor = tree;

                for (let i = 0; i < segments.length; i++) {
                    const isLast = i === segments.length - 1;
                    let seg = segments[i];

                    // "sap-ingress=100" → "sap-ingress 100"
                    let keySeg = seg;
                    const eqIdx = seg.indexOf("=");
                    if (eqIdx !== -1) {
                        keySeg = seg.slice(0, eqIdx) + " " + seg.slice(eqIdx + 1);
                    }

                    if (!isLast) {
                        if (!cursor[keySeg] || typeof cursor[keySeg] !== "object") {
                            cursor[keySeg] = {};
                        }
                        cursor = cursor[keySeg];
                    } else {
                        // Insert value at final segment
                        const cleaned = stripModulePrefixes(value);

                        // FIX #2: collapse "service { service { … }}" and similar
                        const collapsed = collapseDoubleContainer(cursor, keySeg, cleaned);

                        if (!cursor[keySeg] || typeof cursor[keySeg] !== "object") {
                            cursor[keySeg] = {};
                        }
                        mergeDeep(cursor[keySeg], collapsed);
                    }
                }
            }

            return tree;
        };

        // ---------- FIX 1: improved list-key detection ----------
        const listKeyFor = (listName, item) => {
            // 1. <listName>-policy-name (for sap-ingress)
            const pol = `${listName}-policy-name`;
            if (item[pol]) return { id: item[pol], keyField: pol };

            // 2. <listName>-name
            const name = `${listName}-name`;
            if (item[name]) return { id: item[name], keyField: name };

            // 3. <listName>-id
            const idKey = `${listName}-id`;
            if (item[idKey]) return { id: item[idKey], keyField: idKey };

            // fallback: any "*-name"
            const nk = Object.keys(item).find(k => k.endsWith("-name") && typeof item[k] !== "object");
            if (nk) return { id: item[nk], keyField: nk };

            // fallback: any "*-id"
            const ik = Object.keys(item).find(k => k.endsWith("-id") && typeof item[k] !== "object");
            if (ik) return { id: item[ik], keyField: ik };

            // fallback: first primitive
            const fp = Object.entries(item).find(([k, v]) => typeof v === "string" || typeof v === "number");
            if (fp) return { id: fp[1], keyField: fp[0] };

            return { id: null, keyField: null };
        };

        // ---------- Renderer ----------
        const renderTree = (obj, indent = 0, omitKeys = new Set()) => {
            const pad = " ".repeat(indent);
            let out = "";

            for (const [key, value] of Object.entries(obj)) {

                if (omitKeys.has(key)) continue;

                if (indent === 0 && key === "configure") {
                    out += `configure {\n`;
                    out += renderTree(value, indent + 4);
                    out += `}\n`;
                    continue;
                }

                // container
                if (value && typeof value === "object" && !Array.isArray(value)) {
                    const sp = key.indexOf(" ");
                    if (sp !== -1) {
                        const head = key.slice(0, sp);
                        const arg = key.slice(sp + 1);
                        const argStr = arg.includes(" ") ? `"${arg}"` : arg;
                        out += `${pad}${head} ${argStr} {\n`;
                    } else {
                        out += `${pad}${key} {\n`;
                    }
                    out += renderTree(value, indent + 4);
                    out += `${pad}}\n`;
                    continue;
                }

                // list
                if (Array.isArray(value)) {
                    for (const item of value) {
                        const { id, keyField } = listKeyFor(key, item);

                        const omit = new Set(omitKeys);
                        if (keyField) omit.add(keyField);

                        let idStr = "";
                        if (id !== null && id !== undefined) {
                            idStr = typeof id === "string" && id.includes(" ")
                                ? ` "${id}"`
                                : ` ${id}`;
                        }

                        out += `${pad}${key}${idStr} {\n`;
                        out += renderTree(item, indent + 4, omit);
                        out += `${pad}}\n`;
                    }
                    continue;
                }

                // leaf
                if (typeof value === "string" || typeof value === "number") {
                    const val = typeof value === "string" && value.includes(" ") ? `"${value}"` : value;
                    out += `${pad}${key} ${val}\n`;
                    continue;
                }

                if (typeof value === "boolean") {
                    out += value ? `${pad}${key}\n` : `${pad}no ${key}\n`;
                    continue;
                }
            }

            return out;
        };

        // ---------- MAIN ----------
        let result = "";
        for (const [deviceId, ops] of Object.entries(sitesConfigs)) {
            const tree = buildTreeFromOps(ops);
            result += `# device ${deviceId}\n`;
            result += renderTree(tree, 0);
            result += `\n`;
        }

        return result;
    }

    getsitesConfigs(intentType, intentTypeVersion, target, config) {
        this.updateDeviceCache();

        const global = this.getGlobalParameters(intentType, intentTypeVersion, target, config);

        let sitesConfigs = {};
        this.getSiteParameters(intentType, intentTypeVersion, target, config, this.deviceCache).forEach(site => {
            const neId = site["ne-id"];
            site["ne-name"] = this.deviceCache[neId];
            const objects = this.getSiteObjects(intentType, intentTypeVersion, target, global, site, "sync");

          if (!(neId in sitesConfigs))
            sitesConfigs[neId] = {};

            for (const objectName in objects) {
                if ("config" in objects[objectName]) {
                    sitesConfigs[neId][objectName] = objects[objectName].config;
                }
            }
        });

        return sitesConfigs;
    }
    
    getConfig(input) {
        const target = input.getTarget();
        const intentType = input.getIntentType();
        const intentTypeVersion = input.getIntentTypeVersion();
        const config = JSON.parse(input.getJsonIntentConfiguration())[0];
        let sitesConfigs = this.getsitesConfigs(intentType, intentTypeVersion, target, config);

        logger.info("config json: {}", JSON.stringify(sitesConfigs))
        let cfg = this.toMdCli(sitesConfigs);
        logger.info("config mdcli: {}", cfg);

        return '<config xmlns="http://www.nokia.com/management-solutions/reference-action-intent">'+cfg+'</config>';
    }

    getState(intentType, intentTypeVersion, target, config, topology) {
        let sitesConfigs = this.getsitesConfigs(intentType, intentTypeVersion, target, config);
        // return {'configuration': this.toMdCli(sitesConfigs)};

        let output = {};
        for (const [deviceId, configBlocks] of Object.entries(sitesConfigs)) {
            output[deviceId] = {}

            for (const [key, data] of Object.entries(configBlocks)) {
                output[deviceId][data.target] = data.value
            }
        }
        return {'configuration': JSON.stringify(output, null, 4)};
    }
}

new CustomIntentHandler();