/********************************************************************************
 * INTENT-TYPE USED FOR NSP DEVICE CONFIGURATION (DAY 1)
 *   Vendor: {{ vendor }}
 *   Device families: {{ family }}
 *   Device version: {{ version }}
 * 
 * DISCLAIMER:
 *   This intent-type was auto-generated by the NSP Intent Manager extension
 *   for Visual Studio Code. Current status of intent-types generated using
 *   this VS Code extension is experimental!
 * 
 *   To use in production environments, extended testing must be considered:
 *   functionality, robustness, usability, performance, and scale.
 * 
 *   If you find issues around the generator tool or the generated intent-
 *   types, please raise issues in the GitHub repository or contribute
 *   back your code changes!
 * 
 * (c) 2026 by Nokia
 ********************************************************************************/

import { IntentHandler }  from 'common/IntentHandler.mjs';
import { NSP } from 'common/NSP.mjs';

class CustomIntentHandler extends IntentHandler {
    constructor() {
        super();
        NSP.checkRelease(24, 11);
    }

    getSitesCfg(intentType, intentTypeVersion, target, config) {
        this.updateDeviceCache();

        const global = this.getGlobalParameters(intentType, intentTypeVersion, target, config);

        const sitesConfigs = {};
        this.getSiteParameters(intentType, intentTypeVersion, target, config, this.deviceCache).forEach(site => {
            const neId = site["ne-id"];
            site["ne-name"] = this.deviceCache[neId];
            const objects = this.getSiteObjects(intentType, intentTypeVersion, target, global, site, "sync");

            sitesConfigs[neId] = {};
            for (const objectName in objects) {
                if ("config" in objects[objectName]) {
                    sitesConfigs[neId][objectName] = objects[objectName].config;
                }
            }
        });

        return sitesConfigs;
    }
    
    getConfig(input) {
        const target = input.getTarget();
        const intentType = input.getIntentType();
        const intentTypeVersion = input.getIntentTypeVersion();
        const config = JSON.parse(input.getJsonIntentConfiguration())[0];
        let sitesConfigs = this.getSitesCfg(intentType, intentTypeVersion, target, config);

        logger.info("config json: {}", JSON.stringify(sitesConfigs))

        let cfg = "";
        for (const [neId, ops] of Object.entries(sitesConfigs)) {
            cfg += `# device ${neId}\n`;
            cfg += this.getMdCli(neId, ops);
            cfg += `\n`;
        }

        logger.info("config mdcli: {}", cfg);

        return '<config xmlns="http://www.nokia.com/management-solutions/reference-action-intent">'+cfg+'</config>';
    }

    getState(intentType, intentTypeVersion, target, config, topology) {
        let sitesConfigs = this.getSitesCfg(intentType, intentTypeVersion, target, config);

        let output = {};
        for (const [deviceId, configBlocks] of Object.entries(sitesConfigs)) {
            output[deviceId] = {}

            for (const [key, data] of Object.entries(configBlocks)) {
                output[deviceId][data.target] = data.value
            }
        }
        return {'configuration': JSON.stringify(output, null, 4)};
    }
}

new CustomIntentHandler();